### ISSUE TITLE
Can make this LDAP access token instead of x-api-key

### ISSUE THREAD

**Issue by rengan76** [shlinkio/shlink-js-sdk#111]
I want to use LDAP access token instead of x-api-key is this possible?

**Comment by acelaya** [comment]
Slink does not integrate with LDaP. You'll need to orchestrate the login and fetch the corresponding API key for the logged-in user.

**Comment by BloodyIron** [comment]
I have to say not having any interest in LDAP/AD/other-auth integration is a huge hamstring for shlink to be used in a business setting. I'm literally deciding right now if I'm going to use Shlink, Yourls, or something else for my business. And for my use-case it requires the ability to have user/password logins for the management intereface as a minimum (which I don't think is the case with shlink in any way, and this is separate from the API key aspect), and that's before my additional requirement for LDAP/AD integration for central-authentication management of my staff.

Up until finding this github issue/response (which is clearly a rather recent thread being 2024 no less) I was leaning towards Shlink over Yourls. But this might be a hard show-stopper for me.

I highly recommend you rethink whether central-authentication integration is on the roadmap for this ecosystem if you have any interest in attracting business clients. I may be the first one raising the matter in this regard, but I guarantee you any business looking at this that's worth their salt, will be looking at this feature very closely (or in this case, the absence of it).

In the end, it is indeed your project to do with as you see fit. I am raising my talking points here in the hopes you may change your mind on this, because I think it would be worthwhile for the future success of Shlink, whether I myself end up using it or not.

Either way, thank you for continuing to do cool FOSS stuff, and I hope you see the wisdom in what I speak to here. Have a nice weekend!
